version: "3.9"
services:
  express:
    container_name: summarizer
    build:
      context: ./
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules #empty mount to not overwrite node_modules
    environment:
      - NODE_ENV="development"
